version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - chirps

  database:
    image: mysql:8.3
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chirps
    volumes:
      - chirps-db:/var/lib/mysql
    networks:
      - chirps

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - chirps-mail:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - chirps

volumes:
  chirps-db:
  chirps-mail:

networks:
  chirps:
