version: "3.9"

services:
  database:
    image: mysql:8.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chirps
    volumes:
      - chirps:/var/lib/mysql

volumes:
  chirps:
