version: "3.9"

services:
  database:
    image: mysql:8.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chirps
    volumes:
      - chirps-db:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - chirps-mail:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  chirps-db:
  chirps-mail:
